mysql -h ${MARIADB_SERVICE_HOST} -u root \
    -p${DB_ROOT_PASSWORD} mysql <<EOF
CREATE DATABASE IF NOT EXISTS ${DESIGNATE_DB_NAME} CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON ${DESIGNATE_DB_NAME}.* TO
    '${DESIGNATE_DB_USER}'@'%' IDENTIFIED BY '${DESIGNATE_DB_PASSWORD}'
CREATE DATABASE IF NOT EXISTS ${DESIGNATE_DB_NAME}_pool_manager CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON ${DESIGNATE_DB_NAME}_pool_manager.* TO
    '${DESIGNATE_DB_USER}'@'%' IDENTIFIED BY '${DESIGNATE_DB_PASSWORD}'
EOF